# Testdata for CatBoost servables

package(default_visibility = ["//tensorflow_serving:internal"])

licenses(["notice"])  # Apache 2.0

filegroup(
    name = "all_files",
    srcs = glob(
        ["**/*"],
        exclude = [
            "**/METADATA",
            "**/OWNERS",
        ],
    ),
)
